let
    Source = Csv.Document(File.Contents("C:\Users\abzav\Desktop\Adventure Works Dashboard\AW Dataset\AW_Customer.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerKey", Int64.Type}, {"Customer ID", type text}, {"Customer", type text}, {"City", type text}, {"State-Province", type text}, {"Country-Region", type text}, {"Postal Code", type text}}),
    #"Uppercased Text" = Table.TransformColumns(#"Changed Type",{{"Country-Region", Text.Upper, type text}})
in
    #"Uppercased Text"